--------------------------------------------------------
--  File created - Tuesday-May-19-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "VAS_PLATFORM"."USERS" 
   (	"USER_ID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"FULL_NAME" VARCHAR2(100 BYTE), 
	"STATUS" NUMBER(1,0) DEFAULT 1, 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSACTION_LOGS
--------------------------------------------------------

  CREATE TABLE "VAS_PLATFORM"."TRANSACTION_LOGS" 
   (	"LOG_ID" NUMBER, 
	"ACTION_TYPE" VARCHAR2(50 BYTE), 
	"SUBSCRIBER_ID" NUMBER, 
	"SERVICE_ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBSCRIPTIONS
--------------------------------------------------------

  CREATE TABLE "VAS_PLATFORM"."SUBSCRIPTIONS" 
   (	"SUBSCRIPTION_ID" NUMBER, 
	"SUBSCRIBER_ID" NUMBER, 
	"SERVICE_ID" NUMBER, 
	"START_DATE" DATE DEFAULT SYSDATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'ACTIVE'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBSCRIBERS
--------------------------------------------------------

  CREATE TABLE "VAS_PLATFORM"."SUBSCRIBERS" 
   (	"SUBSCRIBER_ID" NUMBER, 
	"MSISDN" VARCHAR2(20 BYTE), 
	"FULL_NAME" VARCHAR2(100 BYTE), 
	"BALANCE" NUMBER(10,2) DEFAULT 0, 
	"STATUS" NUMBER(1,0) DEFAULT 1, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"PASSWORD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVICES
--------------------------------------------------------

  CREATE TABLE "VAS_PLATFORM"."SERVICES" 
   (	"SERVICE_ID" NUMBER, 
	"SERVICE_NAME" VARCHAR2(100 BYTE), 
	"SERVICE_TYPE" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER(10,2), 
	"STATUS" NUMBER(1,0) DEFAULT 1, 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ONE_TIME_PURCHASES
--------------------------------------------------------

  CREATE TABLE "VAS_PLATFORM"."ONE_TIME_PURCHASES" 
   (	"PURCHASE_ID" NUMBER, 
	"SUBSCRIBER_ID" NUMBER, 
	"SERVICE_ID" NUMBER, 
	"PURCHASE_DATE" DATE DEFAULT SYSDATE, 
	"AMOUNT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into VAS_PLATFORM.USERS
SET DEFINE OFF;
Insert into VAS_PLATFORM.USERS (USER_ID,USERNAME,PASSWORD,FULL_NAME,STATUS,CREATED_AT) values (1,'admin','admin123','VAS Platform Admin',1,to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.USERS (USER_ID,USERNAME,PASSWORD,FULL_NAME,STATUS,CREATED_AT) values (2,'vodafone_ops','ops123','Vodafone Operations User',1,to_date('16-MAY-26','DD-MON-RR'));
REM INSERTING into VAS_PLATFORM.TRANSACTION_LOGS
SET DEFINE OFF;
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (7,'BUY_SERVICE',2,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (8,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (255,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (257,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (258,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (259,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (261,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (262,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (263,'BUY_SERVICE',5,8,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (9,'CANCEL_SUBSCRIPTION',1,1,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (10,'BUY_SERVICE',1,1,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (11,'BUY_SERVICE',4,1,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (12,'BUY_SERVICE',1,2,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (13,'BUY_SERVICE',1,3,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (14,'CANCEL_SUBSCRIPTION',1,3,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (15,'CANCEL_SUBSCRIPTION',1,2,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (16,'CANCEL_SUBSCRIPTION',1,1,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (17,'BUY_SERVICE',1,3,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (18,'CANCEL_SUBSCRIPTION',1,3,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (19,'BUY_SERVICE',2,2,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (20,'CANCEL_SUBSCRIPTION',2,2,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (21,'BUY_SERVICE',2,3,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (22,'BUY_SERVICE',2,4,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (23,'BUY_SERVICE',2,2,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (24,'CANCEL_SUBSCRIPTION',2,4,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (25,'BUY_SERVICE',1,2,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (26,'BUY_SERVICE',1,1,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (27,'BUY_SERVICE',1,3,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (28,'BUY_SERVICE',1,4,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (29,'CANCEL_SUBSCRIPTION',1,3,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (30,'CANCEL_SUBSCRIPTION',1,4,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (31,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (32,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (33,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (34,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (35,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (36,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (37,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (44,'BUY_SERVICE',1,8,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (57,'BUY_SERVICE',1,3,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (58,'BUY_SERVICE',1,4,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (59,'CANCEL_SUBSCRIPTION',1,3,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (64,'BUY_SERVICE',1,3,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (65,'CANCEL_SUBSCRIPTION',1,3,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (66,'BUY_SERVICE',1,3,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (67,'CANCEL_SUBSCRIPTION',1,3,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (68,'BUY_SERVICE',1,3,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (69,'CANCEL_SUBSCRIPTION',1,3,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (70,'BUY_SERVICE',1,3,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (71,'CANCEL_SUBSCRIPTION',1,3,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (72,'BUY_SERVICE',1,3,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (73,'BUY_SERVICE',1,8,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (74,'BUY_SERVICE',1,8,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (76,'BUY_SERVICE',1,8,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (77,'BUY_SERVICE',1,8,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (78,'BUY_SERVICE',1,8,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (80,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (83,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (85,'CANCEL_SUBSCRIPTION',1,1,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (86,'CANCEL_SUBSCRIPTION',1,3,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (87,'CANCEL_SUBSCRIPTION',1,4,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (88,'BUY_SERVICE',1,1,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (89,'CANCEL_SUBSCRIPTION',1,1,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (90,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (93,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (95,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (98,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (100,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (101,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (102,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (104,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (105,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (106,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (107,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (109,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (110,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (111,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (112,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (114,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (115,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (116,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (118,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (121,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (123,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (126,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (128,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (131,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (133,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (136,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (138,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (139,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (140,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (142,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (144,'CANCEL_SUBSCRIPTION',1,2,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (145,'BUY_SERVICE',1,2,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (146,'CANCEL_SUBSCRIPTION',1,2,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (148,'CANCEL_SUBSCRIPTION',1,2,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (161,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('17-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (162,'BUY_SERVICE',1,4,'Service purchased successfully',to_date('17-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (163,'CANCEL_SUBSCRIPTION',1,4,'Subscription cancelled successfully',to_date('17-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (181,'BUY_SERVICE',1,2,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (182,'BUY_SERVICE',1,1,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (183,'BUY_SERVICE',1,3,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (184,'BUY_SERVICE',1,4,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (188,'CANCEL_SUBSCRIPTION',1,1,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (189,'BUY_SERVICE',1,1,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (190,'BUY_SERVICE',1,2,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (201,'BUY_SERVICE',1,3,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (202,'CANCEL_SUBSCRIPTION',1,3,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (203,'BUY_SERVICE',1,3,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (209,'BUY_SERVICE',1,1,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (210,'BUY_SERVICE',1,2,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (211,'BUY_SERVICE',1,3,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (212,'BUY_SERVICE',1,4,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (214,'CANCEL_SUBSCRIPTION',1,2,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (215,'BUY_SERVICE',1,2,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (226,'BUY_SERVICE',5,3,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (228,'BUY_SERVICE',5,1,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (232,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (234,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (237,'BUY_SERVICE',5,5,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (241,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (244,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (246,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (250,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (253,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (256,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (260,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (1,'TEST',null,null,'Log procedure test successful',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (2,'BUY_SERVICE',1,1,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (3,'CANCEL_SUBSCRIPTION',1,1,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (4,'BUY_SERVICE',1,1,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (5,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (6,'BUY_SERVICE',2,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (38,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (39,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (40,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (41,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (42,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (43,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (45,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (46,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (47,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (48,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (49,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (50,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (51,'BUY_SERVICE',1,8,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (52,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (53,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (54,'BUY_SERVICE',1,8,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (55,'BUY_SERVICE',1,8,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (56,'BUY_SERVICE',1,8,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (60,'BUY_SERVICE',1,3,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (61,'CANCEL_SUBSCRIPTION',1,3,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (62,'BUY_SERVICE',1,3,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (63,'CANCEL_SUBSCRIPTION',1,3,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (75,'BUY_SERVICE',1,8,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (79,'BUY_SERVICE',1,8,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (81,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (82,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (84,'CANCEL_SUBSCRIPTION',1,2,'Subscription cancelled successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (91,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (92,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (94,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (96,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (97,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (99,'BUY_SERVICE',1,7,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (103,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (108,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (113,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (117,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (119,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (120,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (122,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (124,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (125,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (127,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (129,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (130,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (132,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (134,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (135,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (137,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (141,'BUY_SERVICE',1,5,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (143,'BUY_SERVICE',1,2,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (147,'BUY_SERVICE',1,2,'Service purchased successfully',to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (185,'CANCEL_SUBSCRIPTION',1,2,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (186,'CANCEL_SUBSCRIPTION',1,1,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (187,'BUY_SERVICE',1,1,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (191,'CANCEL_SUBSCRIPTION',1,2,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (192,'BUY_SERVICE',1,2,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (193,'CANCEL_SUBSCRIPTION',1,2,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (194,'BUY_SERVICE',1,2,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (195,'CANCEL_SUBSCRIPTION',1,2,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (196,'BUY_SERVICE',1,2,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (197,'CANCEL_SUBSCRIPTION',1,2,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (198,'BUY_SERVICE',1,2,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (199,'CANCEL_SUBSCRIPTION',1,2,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (200,'CANCEL_SUBSCRIPTION',1,3,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (204,'CANCEL_SUBSCRIPTION',1,3,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (205,'BUY_SERVICE',1,3,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (206,'CANCEL_SUBSCRIPTION',1,3,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (207,'CANCEL_SUBSCRIPTION',1,4,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (208,'CANCEL_SUBSCRIPTION',1,1,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (213,'CANCEL_SUBSCRIPTION',1,4,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (216,'CANCEL_SUBSCRIPTION',1,2,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (217,'BUY_SERVICE',1,2,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (218,'BUY_SERVICE',1,8,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (219,'BUY_SERVICE',1,8,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (220,'BUY_SERVICE',1,8,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (221,'CANCEL_SUBSCRIPTION',1,3,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (222,'CANCEL_SUBSCRIPTION',1,2,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (223,'CANCEL_SUBSCRIPTION',1,1,'Subscription cancelled successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (224,'BUY_SERVICE',1,1,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (225,'BUY_SERVICE',5,2,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (227,'BUY_SERVICE',5,4,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (229,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (230,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (231,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (233,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (235,'BUY_SERVICE',5,5,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (236,'BUY_SERVICE',5,5,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (238,'BUY_SERVICE',5,5,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (239,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (240,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (242,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (243,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (245,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (247,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (248,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (249,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (251,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (252,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.TRANSACTION_LOGS (LOG_ID,ACTION_TYPE,SUBSCRIBER_ID,SERVICE_ID,DESCRIPTION,CREATED_AT) values (254,'BUY_SERVICE',5,6,'Service purchased successfully',to_date('18-MAY-26','DD-MON-RR'));
REM INSERTING into VAS_PLATFORM.SUBSCRIPTIONS
SET DEFINE OFF;
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (3,1,1,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (4,4,1,to_date('16-MAY-26','DD-MON-RR'),null,'ACTIVE');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (5,1,2,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (6,1,3,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (7,1,3,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (8,2,2,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (9,2,3,to_date('16-MAY-26','DD-MON-RR'),null,'ACTIVE');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (10,2,4,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (11,2,2,to_date('16-MAY-26','DD-MON-RR'),null,'ACTIVE');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (12,1,2,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (13,1,1,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (14,1,3,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (15,1,4,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (16,1,3,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (17,1,4,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (20,1,3,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (21,1,3,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (22,1,3,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (23,1,3,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (24,1,3,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (25,1,1,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (27,1,2,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (41,1,4,to_date('17-MAY-26','DD-MON-RR'),to_date('17-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (61,1,2,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (62,1,1,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (63,1,3,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (64,1,4,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (66,1,1,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (67,1,2,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (72,1,3,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (73,1,3,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (75,1,1,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (76,1,2,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (77,1,3,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (78,1,4,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (79,1,2,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (83,5,3,to_date('18-MAY-26','DD-MON-RR'),null,'ACTIVE');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (85,5,1,to_date('18-MAY-26','DD-MON-RR'),null,'ACTIVE');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (1,1,1,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (2,1,1,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (18,1,3,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (19,1,3,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (26,1,2,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (28,1,2,to_date('16-MAY-26','DD-MON-RR'),to_date('16-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (65,1,1,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (68,1,2,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (69,1,2,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (70,1,2,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (71,1,2,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (74,1,3,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (80,1,2,to_date('18-MAY-26','DD-MON-RR'),to_date('18-MAY-26','DD-MON-RR'),'CANCELLED');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (81,1,1,to_date('18-MAY-26','DD-MON-RR'),null,'ACTIVE');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (82,5,2,to_date('18-MAY-26','DD-MON-RR'),null,'ACTIVE');
Insert into VAS_PLATFORM.SUBSCRIPTIONS (SUBSCRIPTION_ID,SUBSCRIBER_ID,SERVICE_ID,START_DATE,END_DATE,STATUS) values (84,5,4,to_date('18-MAY-26','DD-MON-RR'),null,'ACTIVE');
REM INSERTING into VAS_PLATFORM.SUBSCRIBERS
SET DEFINE OFF;
Insert into VAS_PLATFORM.SUBSCRIBERS (SUBSCRIBER_ID,MSISDN,FULL_NAME,BALANCE,STATUS,CREATED_AT,PASSWORD) values (5,'905555555555','Ç?nar Y?ld?z',0,1,to_date('18-MAY-26','DD-MON-RR'),'12345');
Insert into VAS_PLATFORM.SUBSCRIBERS (SUBSCRIBER_ID,MSISDN,FULL_NAME,BALANCE,STATUS,CREATED_AT,PASSWORD) values (6,'905311231212','Meriç Gumus',1230,1,to_date('16-MAY-26','DD-MON-RR'),'12345');
Insert into VAS_PLATFORM.SUBSCRIBERS (SUBSCRIBER_ID,MSISDN,FULL_NAME,BALANCE,STATUS,CREATED_AT,PASSWORD) values (1,'905428871104','Özgür Do?an Güne?',5075,1,to_date('16-MAY-26','DD-MON-RR'),'12345');
Insert into VAS_PLATFORM.SUBSCRIBERS (SUBSCRIBER_ID,MSISDN,FULL_NAME,BALANCE,STATUS,CREATED_AT,PASSWORD) values (2,'905424445566','Ugur Beyaz',1100,1,to_date('16-MAY-26','DD-MON-RR'),'12345');
Insert into VAS_PLATFORM.SUBSCRIBERS (SUBSCRIBER_ID,MSISDN,FULL_NAME,BALANCE,STATUS,CREATED_AT,PASSWORD) values (3,'905427778899','Suzan Kendter',100,1,to_date('16-MAY-26','DD-MON-RR'),'12345');
Insert into VAS_PLATFORM.SUBSCRIBERS (SUBSCRIBER_ID,MSISDN,FULL_NAME,BALANCE,STATUS,CREATED_AT,PASSWORD) values (4,'905420001122','Ayse Durmaz',75,1,to_date('16-MAY-26','DD-MON-RR'),'12345');
REM INSERTING into VAS_PLATFORM.SERVICES
SET DEFINE OFF;
Insert into VAS_PLATFORM.SERVICES (SERVICE_ID,SERVICE_NAME,SERVICE_TYPE,PRICE,STATUS,CREATED_AT) values (1,'Super Cool','SUBSCRIPTION',25,1,to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.SERVICES (SERVICE_ID,SERVICE_NAME,SERVICE_TYPE,PRICE,STATUS,CREATED_AT) values (2,'Student Pass','SUBSCRIPTION',40,1,to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.SERVICES (SERVICE_ID,SERVICE_NAME,SERVICE_TYPE,PRICE,STATUS,CREATED_AT) values (3,'Gamer Pack','SUBSCRIPTION',55,1,to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.SERVICES (SERVICE_ID,SERVICE_NAME,SERVICE_TYPE,PRICE,STATUS,CREATED_AT) values (4,'Safe Internet','SUBSCRIPTION',15,1,to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.SERVICES (SERVICE_ID,SERVICE_NAME,SERVICE_TYPE,PRICE,STATUS,CREATED_AT) values (5,'One-Time 15 GB Internet','ONE_TIME',30,1,to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.SERVICES (SERVICE_ID,SERVICE_NAME,SERVICE_TYPE,PRICE,STATUS,CREATED_AT) values (6,'One-Time Roaming Day Pass','ONE_TIME',90,1,to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.SERVICES (SERVICE_ID,SERVICE_NAME,SERVICE_TYPE,PRICE,STATUS,CREATED_AT) values (7,'One-Time 5 GB Internet','ONE_TIME',12,1,to_date('16-MAY-26','DD-MON-RR'));
Insert into VAS_PLATFORM.SERVICES (SERVICE_ID,SERVICE_NAME,SERVICE_TYPE,PRICE,STATUS,CREATED_AT) values (8,'One-Time International Call 30 Min','ONE_TIME',45,1,to_date('16-MAY-26','DD-MON-RR'));
REM INSERTING into VAS_PLATFORM.ONE_TIME_PURCHASES
SET DEFINE OFF;
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (3,2,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (4,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (5,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (6,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (7,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (8,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (9,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (10,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (11,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (18,1,8,to_date('16-MAY-26','DD-MON-RR'),45);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (31,1,8,to_date('16-MAY-26','DD-MON-RR'),45);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (32,1,8,to_date('16-MAY-26','DD-MON-RR'),45);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (34,1,8,to_date('16-MAY-26','DD-MON-RR'),45);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (35,1,8,to_date('16-MAY-26','DD-MON-RR'),45);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (36,1,8,to_date('16-MAY-26','DD-MON-RR'),45);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (38,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (41,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (42,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (45,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (47,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (50,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (52,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (53,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (54,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (56,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (57,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (58,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (59,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (61,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (62,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (63,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (64,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (66,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (67,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (68,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (70,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (73,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (75,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (78,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (80,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (83,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (85,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (88,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (90,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (91,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (92,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (94,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (101,1,7,to_date('17-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (127,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (129,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (132,5,5,to_date('18-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (136,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (139,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (141,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (145,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (148,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (151,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (155,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (1,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (2,2,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (12,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (13,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (14,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (15,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (16,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (17,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (19,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (20,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (21,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (22,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (23,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (24,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (25,1,8,to_date('16-MAY-26','DD-MON-RR'),45);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (26,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (27,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (28,1,8,to_date('16-MAY-26','DD-MON-RR'),45);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (29,1,8,to_date('16-MAY-26','DD-MON-RR'),45);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (30,1,8,to_date('16-MAY-26','DD-MON-RR'),45);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (33,1,8,to_date('16-MAY-26','DD-MON-RR'),45);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (37,1,8,to_date('16-MAY-26','DD-MON-RR'),45);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (39,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (40,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (43,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (44,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (46,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (48,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (49,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (51,1,7,to_date('16-MAY-26','DD-MON-RR'),12);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (55,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (60,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (65,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (69,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (71,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (72,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (74,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (76,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (77,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (79,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (81,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (82,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (84,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (86,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (87,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (89,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (93,1,5,to_date('16-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (121,1,8,to_date('18-MAY-26','DD-MON-RR'),45);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (122,1,8,to_date('18-MAY-26','DD-MON-RR'),45);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (123,1,8,to_date('18-MAY-26','DD-MON-RR'),45);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (124,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (125,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (126,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (128,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (130,5,5,to_date('18-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (131,5,5,to_date('18-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (133,5,5,to_date('18-MAY-26','DD-MON-RR'),30);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (134,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (135,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (137,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (138,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (140,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (142,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (143,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (144,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (146,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (147,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (149,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (150,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (152,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (153,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (154,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (156,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (157,5,6,to_date('18-MAY-26','DD-MON-RR'),90);
Insert into VAS_PLATFORM.ONE_TIME_PURCHASES (PURCHASE_ID,SUBSCRIBER_ID,SERVICE_ID,PURCHASE_DATE,AMOUNT) values (158,5,8,to_date('18-MAY-26','DD-MON-RR'),45);
--------------------------------------------------------
--  DDL for Index SYS_C008278
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAS_PLATFORM"."SYS_C008278" ON "VAS_PLATFORM"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008279
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAS_PLATFORM"."SYS_C008279" ON "VAS_PLATFORM"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008298
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAS_PLATFORM"."SYS_C008298" ON "VAS_PLATFORM"."TRANSACTION_LOGS" ("LOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008290
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAS_PLATFORM"."SYS_C008290" ON "VAS_PLATFORM"."SUBSCRIPTIONS" ("SUBSCRIPTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008281
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAS_PLATFORM"."SYS_C008281" ON "VAS_PLATFORM"."SUBSCRIBERS" ("SUBSCRIBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008282
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAS_PLATFORM"."SYS_C008282" ON "VAS_PLATFORM"."SUBSCRIBERS" ("MSISDN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008287
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAS_PLATFORM"."SYS_C008287" ON "VAS_PLATFORM"."SERVICES" ("SERVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008295
--------------------------------------------------------

  CREATE UNIQUE INDEX "VAS_PLATFORM"."SYS_C008295" ON "VAS_PLATFORM"."ONE_TIME_PURCHASES" ("PURCHASE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "VAS_PLATFORM"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "VAS_PLATFORM"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "VAS_PLATFORM"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VAS_PLATFORM"."USERS" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSACTION_LOGS
--------------------------------------------------------

  ALTER TABLE "VAS_PLATFORM"."TRANSACTION_LOGS" ADD PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBSCRIPTIONS
--------------------------------------------------------

  ALTER TABLE "VAS_PLATFORM"."SUBSCRIPTIONS" MODIFY ("SUBSCRIBER_ID" NOT NULL ENABLE);
  ALTER TABLE "VAS_PLATFORM"."SUBSCRIPTIONS" MODIFY ("SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "VAS_PLATFORM"."SUBSCRIPTIONS" ADD PRIMARY KEY ("SUBSCRIPTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBSCRIBERS
--------------------------------------------------------

  ALTER TABLE "VAS_PLATFORM"."SUBSCRIBERS" MODIFY ("MSISDN" NOT NULL ENABLE);
  ALTER TABLE "VAS_PLATFORM"."SUBSCRIBERS" ADD PRIMARY KEY ("SUBSCRIBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VAS_PLATFORM"."SUBSCRIBERS" ADD UNIQUE ("MSISDN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICES
--------------------------------------------------------

  ALTER TABLE "VAS_PLATFORM"."SERVICES" MODIFY ("SERVICE_NAME" NOT NULL ENABLE);
  ALTER TABLE "VAS_PLATFORM"."SERVICES" MODIFY ("SERVICE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "VAS_PLATFORM"."SERVICES" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "VAS_PLATFORM"."SERVICES" ADD CONSTRAINT "CHK_SERVICE_TYPE" CHECK (SERVICE_TYPE IN ('SUBSCRIPTION', 'ONE_TIME')) ENABLE;
  ALTER TABLE "VAS_PLATFORM"."SERVICES" ADD PRIMARY KEY ("SERVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ONE_TIME_PURCHASES
--------------------------------------------------------

  ALTER TABLE "VAS_PLATFORM"."ONE_TIME_PURCHASES" MODIFY ("SUBSCRIBER_ID" NOT NULL ENABLE);
  ALTER TABLE "VAS_PLATFORM"."ONE_TIME_PURCHASES" MODIFY ("SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "VAS_PLATFORM"."ONE_TIME_PURCHASES" ADD PRIMARY KEY ("PURCHASE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBSCRIPTIONS
--------------------------------------------------------

  ALTER TABLE "VAS_PLATFORM"."SUBSCRIPTIONS" ADD CONSTRAINT "FK_SUB_SUBSCRIBER" FOREIGN KEY ("SUBSCRIBER_ID")
	  REFERENCES "VAS_PLATFORM"."SUBSCRIBERS" ("SUBSCRIBER_ID") ENABLE;
  ALTER TABLE "VAS_PLATFORM"."SUBSCRIPTIONS" ADD CONSTRAINT "FK_SUB_SERVICE" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "VAS_PLATFORM"."SERVICES" ("SERVICE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ONE_TIME_PURCHASES
--------------------------------------------------------

  ALTER TABLE "VAS_PLATFORM"."ONE_TIME_PURCHASES" ADD CONSTRAINT "FK_OTP_SUBSCRIBER" FOREIGN KEY ("SUBSCRIBER_ID")
	  REFERENCES "VAS_PLATFORM"."SUBSCRIBERS" ("SUBSCRIBER_ID") ENABLE;
  ALTER TABLE "VAS_PLATFORM"."ONE_TIME_PURCHASES" ADD CONSTRAINT "FK_OTP_SERVICE" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "VAS_PLATFORM"."SERVICES" ("SERVICE_ID") ENABLE;
